version: '3'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
      - "10051:10051"
    volumes:
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
    environment:
      - DB_SERVER_HOST=zabbix-database
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd

  zabbix-web-apache-mysql:
    image: zabbix/zabbix-web-apache-mysql
    ports:
      - "80:80"
    environment:
      - DB_SERVER_HOST=zabbix-database
      - ZBX_SERVER_HOST=zabbix-server
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=Europe/Berlin
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
  zabbix-database:
    image: mysql:5.7
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
    environment:
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - MYSQL_ROOT_PASSWORD=root_pwd
    volumes:
      - ./dbdata_zabbix:/var/lib/mysql
