#!/bin/sh

_tag="develop"


##########################
#### General Settings ####
##########################

set -e
set -u
#set -x # only for DEBUG

# Make available the functions defined in /lib/lsb/init-functions
. /lib/lsb/init-functions


##########################
#### Global Variables ####
##########################

#_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

_openbaton_base_repo="https://github.com/openbaton/NFVO.git"
_openbaton_plugins="http://get.openbaton.org/plugins/stable/"
_openbaton_generic_vnfm_repo="https://github.com/openbaton/generic-vnfm.git"
_openbaton_fmsystem_repo="https://github.com/openbaton/fm-system.git"
_openbaton_asengine_repo="https://github.com/openbaton/autoscaling-engine.git"
_openbaton_nsengine_repo="https://github.com/openbaton/network-slicing-engine.git"

_base=/opt
_openbaton_base="${_base}/openbaton"
_openbaton_conf="/etc/openbaton"
_openbaton_log="/var/log/openbaton"
_nfvo="${_openbaton_base}/nfvo"
_nfvo_vim_drivers="${_nfvo}/plugins/vim-drivers"
_generic_vnfm="${_openbaton_base}/generic-vnfm"

_installer_folder="${_base}/tmp"
_logfile="${_installer_folder}/log"
_tmpfolder=`mktemp -d`

_user="$(id -un 2>/dev/null || true)"


##################
#### RabbitMQ ####
##################

src_install_message_queue () {
    echo "installing message queue.."
    $_ex 'apt-get install -y rabbitmq-server'
    ulimit -S -n 4096
    $_ex 'rabbitmqctl add_user admin openbaton'
    $_ex 'rabbitmqctl set_user_tags admin administrator'
    $_ex 'rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"'
    $_ex 'rabbitmq-plugins enable rabbitmq_management'
    $_ex 'service rabbitmq-server restart'
    if [ $? -ne 0 ]; then
      echo "ERROR: rabbitmq is not running properly (check the problem in /var/log/rabbitmq)"
      exit 1
    fi
}

src_configure_message_queue () {
  read -p "Enter the rabbitmq broker ip [localhost]: " brokerIp
  export brokerIp=${brokerIp}
  if [ "${brokerIp}" != "" ]; then
      $_ex 'sed -i "s/nfvo.rabbit.brokerIp=localhost/nfvo.rabbit.brokerIp=${brokerIp}/g" /etc/openbaton/openbaton.properties'
  fi

  read -p "Enter the rabbitmq management port [15672]: " managementPort
  export managementPort=${managementPort}
  if [ "${managementPort}" != "" ]; then
    $_ex 'sed -i "s/nfvo.rabbit.management.port=15672/nfvo.rabbit.management.port=${managementPort}/g" /etc/openbaton/openbaton.properties'
  fi
}


#############################
#### VIM-Drivers Plugins ####
#############################

src_download_plugins () {
    echo "Getting OpenBaton Plugins..."
    wget -nH --cut-dirs 2 -r --no-parent  --reject "index.html*" "${_openbaton_plugins}" -P "${_tmpfolder}"
    mkdir -p ${_nfvo_vim_drivers}
    cp -r ${_tmpfolder}/* "${_nfvo_vim_drivers}"
}


####################
#### Open Baton ####
####################

src_prereq () {
    # TODO differentiate between fedora, OS X, ubuntu..
    $_ex 'apt-get update; apt-get -y install openjdk-7-jdk curl wget screen git'
    fix_java_security
}

src_check_environment () {
  _error=0
  echo "Checking environment..."
  check_binary java; _error=$(($_error + $?))
  check_binary javac; _error=$(($_error + $?))
  check_binary curl; _error=$(($_error + $?))
  check_binary screen; _error=$(($_error + $?))
  check_binary wget; _error=$(($_error + $?))
  if [ "0" != "$_error" ]; then
    echo >&2 "FAILED. Please install the above mentioned binaries."
    exit 1
  fi
}

src_create_openbaton_base () {
    echo "Creating the OpenBaton base folder"
    # removing it if exists
    $_ex 'rm -rf '$_openbaton_base
    $_ex 'mkdir -p '$_nfvo
    $_ex 'chown -R '"$_user $_openbaton_base"
}

src_create_openbaton_log () {
    echo "Creating the OpenBaton log folder"
    # removing it if exists
    $_ex 'rm -rf '$_openbaton_log
    $_ex 'mkdir -p '$_openbaton_log
    $_ex 'chown -R '"$_user $_openbaton_log"
}

src_checkout_nfvo () {
    echo "Getting OpenBaton..."
    src_create_openbaton_base
    src_create_openbaton_log
    git clone --recursive "${_openbaton_base_repo}" "${_nfvo}"
    cd "${_nfvo}"
    git checkout ${_tag}
    $_ex 'rm -rf '"${_openbaton_conf}; mkdir -p ${_openbaton_conf}"
    $_ex 'cp '"${_nfvo}/etc/openbaton.properties ${_openbaton_conf}/openbaton.properties"
    $_ex 'cp '"${_nfvo}/etc/keystore.p12 ${_openbaton_conf}/keystore.p12"
}

src_compile_nfvo () {
    echo "compiling the NFVO"
    cd "${_nfvo}"
    ./openbaton.sh compile
    if [ $? -ne 0 ]; then
        echo "ERROR: The compilation of the NFVO failed"
        exit 1
    fi
}

src_start_nfvo () {
    echo "starting the NFVO"
    cd "${_nfvo}"
    ./openbaton.sh start
}

src_deploy_nfvo () {
    src_compile_nfvo
    install_mysql "openbaton.properties"
    src_set_openbaton_password
    src_start_nfvo
}

src_delete_openbaton_password () {
      $_ex 'sed -i "/^nfvo.security.admin.password =/d" /etc/openbaton/openbaton.properties'
}

src_set_openbaton_password () {
    # In case of "noninteractive" FRONTEND the default value will remain valid (user: admin ; password: openbaton)
    if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
        # Turning echo on and off between password reading
        stty -echo
        read -p "Provide the new password for 'admin' user of Open Baton: " openbatonpswd ; echo
        stty echo
        if [ "${openbatonpswd}" != "" ]; then
            export openbatonpswd=${openbatonpswd}
            stty -echo
            read -p "Repeat the password: " openbatonpswd2 ; echo
            stty echo
            export openbatonpswd2=${openbatonpswd2}
            if [ "${openbatonpswd}" = "${openbatonpswd2}" ]; then
                $_ex 'sed -i "s/# nfvo.security.admin.password\ =\ openbaton/nfvo.security.admin.password\ =\ ${openbatonpswd}/g" /etc/openbaton/openbaton.properties'
                return
            fi
        else
            src_set_openbaton_password
        fi
    fi
}


##############################
#### Additional Component ####

src_checkout_additional_component () {
    component_repo_url=${1}
    component_name=${2}                       # the directory on which the repo will be locally cloned
    component_name_fancy="${3}"
    component_properties_file_src="${4}"
    component_properties_file_dest="${5}"
    component_of_minimal_installation="${6}"

    if [ "${DEBIAN_FRONTEND}" != "Noninteractive" -a "${DEBIAN_FRONTEND}" != "noninteractive" ]; then
        # Ask for the specified Additional Component installation
        read -p "Do you want to install also the ${component_name_fancy}? (if you do not, then you can still install it later with 'cd ${_openbaton_base} && git clone ${component_repo_url}') (Y/n): " ac

        if [ "${ac}" = "" -o "${ac}" = "y" -o "${ac}" = "Y" ]; then
            cd "${_openbaton_base}"
            echo "Getting ${component_name_fancy} .."
            git clone --recursive "${component_repo_url}" "${component_name}"
            cd "${component_name}"
            git checkout ${_tag}
            $_ex 'cp '"${component_properties_file_src} ${_openbaton_conf}/${component_properties_file_dest}"
            installed=0
            return
        fi
    fi
    installed=1
}

src_compile_additional_component () {
    component_name=${1}                       # the directory on which the repo has been cloned
    component_name_fancy="${2}"

    echo "Compiling the ${component_name_fancy} .."
    cd "${_openbaton_base}/${component_name}"
    ./${component_name}.sh compile
    if [ $? -ne 0 ]; then
        echo "ERROR: The compilation of the Generic VNFM failed"
        exit 1
    fi
}

src_start_additional_component () {
    component_name=${1}                       # the directory on which the repo has been cloned
    component_name_fancy="${2}"
    
    echo "Starting the ${component_name_fancy} .."
    cd "${_openbaton_base}/${component_name}"
    ./${component_name}.sh start
}

src_deploy_additional_component () {
    src_compile_additional_component ${1} ${2}
    src_start_additional_component ${1} ${2}
}


##############
#### Main ####
##############

src_bootstrap () {
    # install prerq
    src_prereq

    # checkout OpenBaton
    src_checkout_nfvo
    # moved message queue installation part
    src_download_plugins
    # moved message queue installation and configuration part
    src_install_message_queue
    src_configure_message_queue
    # check if all the required libraries are available
    src_check_environment
    # configure the Open Baton security 
    configure_security "openbaton.properties"
    # deploy and compile OpenBaton orchestrator
    src_deploy_nfvo
    #src_delete_openbaton_password

    # checkout the generic VNFM code
    src_checkout_additional_component "${_openbaton_generic_vnfm_repo}" "generic-vnfm" "Generic VNFM" "src/main/resources/application.properties" "openbaton-vnfm-generic.properties" true
    # deploy and compile the Generic VNFM
    if [ "${installed}" = "0" ]; then src_deploy_additional_component "generic-vnfm" "Generic VNFM" ; fi

    # checkout the Fault Management System
    src_checkout_additional_component "${_openbaton_fmsystem_repo}" "fm-system" "Fault Management System (FMS)" "etc/fms.properties" "openbaton-fms.properties" false
    # deploy and compile the Fault Management System
    if [ "${installed}" = "0" ]; then src_deploy_additional_component "fm-system" "Fault Management System (FMS)" ; fi

    # checkout the Auto Scaling Engine
    src_checkout_additional_component "${_openbaton_asengine_repo}" "autoscaling-engine" "Auto Scaling Engine (ASE)" "etc/ase.properties" "openbaton-ase.properties" false
    # deploy and compile the Auto Scaling Engine
    if [ "${installed}" = "0" ]; then src_deploy_additional_component "autoscaling-engine" "Auto Scaling Engine (ASE)" ; fi

    # checkout the Network Slicing Engine
    src_checkout_additional_component "${_openbaton_nsengine_repo}" "network-slicing-engine" "Network Slicing Engine (NSE)" "etc/nse.properties" "openbaton-nse.properties" false
    # deploy and compile the Network Slicing Engine
    if [ "${installed}" = "0" ]; then src_deploy_additional_component "network-slicing-engine" "Network Slicing Engine" ; fi

    echo " * [INFO] Waiting for Open Baton to be up..."
	while ! nc -z localhost 8080; do   
	  	sleep 1 # wait for 1 second before check again
	done
    echo " * [INFO] Now open http://localhost:8080/"

    rm ./bootstrap-src-functions
}

