version: '3'
services:
  nfvo:
    image: openbaton/nfvo:${OB_VERSION}
    depends_on:
      - rabbitmq_broker
      - mysql_server
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_server:3306/openbaton
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
  vnfm_generic:
    image: openbaton/vnfm-generic:${OB_VERSION}
    depends_on:
      - nfvo
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - VNFM_RABBITMQ_BROKERIP=rabbitmq_broker
  plugin_vimdriver_openstack_4j:
    image: openbaton/plugin-vimdriver-openstack-4j:${OB_VERSION}
    depends_on:
      - nfvo
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - RABBITMQ=rabbitmq_broker
  rabbitmq_broker:
    image: rabbitmq:${OB_RABBITMQ_VERSION}
    hostname: openbaton-rabbitmq
    env_file:
      - env/openbaton.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dbdata_rabbit:/var/lib/rabbitmq
  mysql_server:
    image: mysql/mysql-server:${OB_MYSQL_VERSION}
    env_file:
      - env/openbaton.env
    volumes:
      - ./dbdata_nfvo:/var/lib/mysql
volumes:
  dbdata_nfvo:
  dbdata_rabbit:
