version: '3'
services:
  nfvo:
    image: openbaton/nfvo:fix-clients-restart
    depends_on:
      - rabbitmq_broker
      - nfvo_database
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://nfvo_database:3306/openbaton?useSSL=false
    ports:
      - "8080:8080"
  vnfm_generic:
    image: openbaton/vnfm-generic:${OB_VERSION}
    depends_on:
      - nfvo
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - RABBITMQ_HOST=rabbitmq_broker
  plugin_vimdriver_openstack_4j:
    image: openbaton/plugin-vimdriver-openstack-4j:${OB_VERSION}
    depends_on:
      - nfvo
    restart: always
    env_file:
      - env/openbaton.env
    environment:
      - RABBITMQ=rabbitmq_broker
  rabbitmq_broker:
    image: rabbitmq:${OB_RABBITMQ_VERSION}
    env_file:
      - env/openbaton.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dbdata_rabbit:/var/lib/rabbitmq
  nfvo_database:
    image: mysql/mysql-server:${OB_MYSQL_VERSION}
    env_file:
      - env/openbaton.env
    volumes:
      - ./dbdata_nfvo:/var/lib/mysql
  fms_database:
    image: mysql/mysql-server:${OB_MYSQL_VERSION}
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=faultmanagement
      - MYSQL_USER=fmsuser
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./dbdata_fms:/var/lib/mysql
  zabbix_monitoring_plugin:
    image: openbaton/plugin-monitoring-zabbix:${OB_VERSION}
    depends_on:
      - nfvo
    env_file:
      - env/openbaton.env
    environment:
      - ZABBIX_PLUGIN_IP=zabbix_monitoring_plugin
      - FAULTS_CONSUMER_ENDPOINT=http://fault-management-system:9000/alarm/vr
      - ZABBIX_HOST=zabbix_web_apache_mysql
      - RABBITMQ_BROKERIP=rabbitmq_broker
  fault-management-system:
    image: openbaton/fms:latest
    depends_on:
      - nfvo
      - zabbix_monitoring_plugin
      - fms_database
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
      - NFVO_IP=nfvo
      - PLUGIN_IP=zabbix-plugin
      - SPRING_DATASOURCE_URL=jdbc:mysql://fms_database:3306/faultmanagement
  zabbix_server:
    image: zabbix/zabbix-server-mysql:alpine-3.4.10
    ports:
      - "10051:10051"
    env_file:
      - env/zabbix.env
    environment:
      - DB_SERVER_HOST=zabbix_database
    volumes:
      - ./zbx_env/usr/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts:ro
  zabbix_web_apache_mysql:
    image: zabbix/zabbix-web-apache-mysql:alpine-3.4.10
    ports:
      - "80:80"
    env_file:
      - env/zabbix.env
    environment:
      - DB_SERVER_HOST=zabbix_database
      - ZBX_SERVER_HOST=zabbix_server
  zabbix_database:
    image: mysql/mysql-server:5.7
    env_file:
      - env/zabbix.env
    volumes:
      - ./dbdata_zabbix:/var/lib/mysql
volumes:
  dbdata_nfvo:
  dbdata_fms:
  dbdata_rabbit:
  dbdata_zabbix:
